---
admin_project: ocp-workshop
user_count_start: 1
num_users: 5
user_format: user%d
user_password: "openshift"
ocp_bastion: "bastion.{{ guid }}{{ subdomain_base_suffix }}"
bastion_internal: "bastion.{{ guid }}.internal"

ocp_master: "master.{{ guid }}{{ subdomain_base_suffix }}"
ocp_apps_domain: apps.{{ guid }}{{ subdomain_base_suffix }}
ocp_user_needs_quota: "false"
user_count: "{{ num_users }}"

che_project: "che-workspaces"

repo_url: https://github.com/RedHatDemos/SecurityDemos.git
reponame_local: SecurityDemos
reponame: SecurityDemos
demoapp_location: 2019Labs/ProactiveSecurityCompliance/OpenShiftSecurityPipeline/spring-boot-angular-ecommerce

etherpad_text: "Welcome to our OpenShift Workshop!!!\\n\\n"
etherpad_urlprefix: "etherpad-{{ admin_project }}"
etherpad_hostname: "{{ etherpad_urlprefix }}.{{ ocp_apps_domain }}"

guide_urlprefix: "guide-{{ admin_project }}"
guide_hostname: "{{ guide_urlprefix }}.{{ ocp_apps_domain }}"

quota_requests_cpu: 5
quota_limits_cpu: 10
quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'
quota_configmaps: 4
quota_pods: 20
quota_persistentvolumeclaims: 5
quota_services: 15
quota_secrets: 30
quota_requests_storage: 10Gi

quay_pull_user: changeme
quay_pull_password: changeme

set_hostname_suffix: false
oc_kube_config: "/root/.kube/config"
project_suffix: tmp
openshift_cli: oc


###### Gogs defaults
gogs_admin_user: "gogsadmin"
gogs_admin_password: "openshift"

gogs_user: "gogs"
gogs_user_password: "openshift"

gogs_urlprefix: "gogs-{{ admin_project }}"
gogs_hostname: "{{ gogs_urlprefix }}.{{ ocp_apps_domain }}"
gogs_route: "{{ gogs_hostname }}"

gogs_generate_user_format: "{{ user_format }}"

gogs_image_version: 0.11.34
gogs_database_version: 9.6
gogs_route: gogs-{{ project_name }}.127.0.0.1.nip.io
gogs_generate_user_count: 0
gogs_generate_user_format: user%02d

gogs_project_name: gogs
gogs_project_name: "{{ admin_project }}"

gogs_project_display_name: Gogs
gogs_project_desc: Gogs Git Server
gogs_deploy_retry_delay: 30
gogs_deploy_retry_count: 10
ephemeral: false
clean_deploy: false
gogs_service_name: gogs
skip_tls_verify: true
max_mem: 1Gi
min_mem: 128Mi
max_cpu: 400m
min_cpu: 100m

######### Nexus defaults
nexus_urlprefix: "nexus-{{ admin_project }}"
nexus_hostname: "{{ nexus_urlprefix }}.{{ ocp_apps_domain }}"

nexus_max_memory: 2Gi
nexus_min_memory: 512Mi
nexus_max_cpu: 1
nexus_min_cpu: 200m
nexus_volume_capacity: 10Gi

nexus_service_name: nexus

nexus_image_version: 3.20.1

nexus_project_name: nexus
nexus_project_name: "{{ admin_project }}"

nexus_project_display_name: Nexus
nexus_project_desc: Nexus Repository Manager
nexus_admin_user: admin
nexus_admin_password: admin123
current_nexus_admin_password: admin123

ocp_registry_route: unset
