---
- name: Infrastructure Tasks Started

- name: install oscap tools
  yum:
    name:
      - docker
      - openscap-utils
      - openscap-scanner
      - scap-security-guide
      - atomic
  delegate_to: "{{ bastion_internal }}"

- name: ensure docker group exists
  group:
    name: docker
    state: present
  delegate_to: "{{ bastion_internal }}"

- name: enable ssh password
  replace:
    regexp: "PasswordAuthentication no"
    path: /etc/ssh/sshd_config
    replace: "PasswordAuthentication yes"
  delegate_to: "{{ bastion_internal }}"

- name: restart sshd service
  service:
    name: sshd
    state: restarted
  delegate_to: "{{ bastion_internal }}"

- name: retrieve registry route
  shell: "{{ openshift_cli }} get routes --all-namespaces | grep registry | grep -v console | awk '{print $3}'"
  register: image_route

- name: set route name
  set_fact:
    ocp_registry_route: "{{ image_route.stdout }}"

- name: add exposed registry as insecure
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
    backup: yes
  register: reg_result
  delegate_to: "{{ bastion_internal }}"

- name: enable docker service
  service:
    name: docker
    enabled: true
  delegate_to: "{{ bastion_internal }}"

- name: restart docker service
  service:
    name: docker
    state: restarted
  when: reg_result.changed
  delegate_to: "{{ bastion_internal }}"

- name: allow group to use oscap-docker without sudo password
  lineinfile:
    dest: /etc/sudoers
    line: "%docker ALL=NOPASSWD: /usr/bin/oscap-docker"
    validate: '/usr/sbin/visudo -cf %s'
  become: true
  delegate_to: "{{ bastion_internal }}"

- name: create custom jenkins image
  shell: |
    {{ openshift_cli }} new-build -D $'FROM jenkins:latest\nUSER 0\nRUN curl -L https://updates.jenkins-ci.org/download/plugins/ssh-steps/1.2.1/ssh-steps.hpi -o /usr/lib/jenkins/ssh-steps.hpi && chmod 665 /usr/lib/jenkins/ssh-steps.hpi && sed -i '\''s/{ print $1; }/ {a=$1} END{print a}/'\'' /usr/libexec/s2i/run' --to=custom-jenkins -n openshift
  ignore_errors: true

- name: wait for custom jenkins build to finish
  shell: "{{ openshift_cli }} get builds -n openshift | grep custom-jenkins | grep Complete"
  register: result_jenkins
  until: result_jenkins.rc == 0
  retries: 60
  delay: 20

- name: create owasp zap image
  command: "{{ openshift_cli }} new-build --name owasp-zap -l 'role=jenkins-slave' https://github.com/RedHatDemos/SecurityDemos.git --context-dir=2019Labs/ProactiveSecurityCompliance/OpenShiftSecurityPipeline/jenkins-slave-zap -n openshift"
  ignore_errors: true

- name: wait for owasp zap build to finish
  shell: "{{ openshift_cli }} get builds -n openshift | grep owasp-zap | grep Complete"
  register: result_owasp
  until: result_owasp.rc == 0
  retries: 60
  delay: 20

- name: create image management image
  command: "{{ openshift_cli }} new-build --name image-management -l 'role=jenkins-slave' https://github.com/siamaksade/jenkins-slave-skopeo.git -n openshift"
  ignore_errors: true

- name: wait for image mgmt build to finish
  shell: "{{ openshift_cli }} get builds -n openshift | grep image-management | grep Complete"
  register: result_mgmt
  until: result_mgmt.rc == 0
  retries: 60
  delay: 20

- name: check if project {{ admin_project }} exists
  command: "{{ openshift_cli }} get project {{ admin_project }}"
  register: shared_project_result
  ignore_errors: true
  changed_when: false
  tags: always

- name: expose registry
  command: "{{ openshift_cli }} create route passthrough --service=image-registry -n openshift-image-registry "
  tags: always
  ignore_errors: true

- name: create project {{ admin_project }}
  command: "{{ openshift_cli }} new-project {{ admin_project }}"
  when: shared_project_result is failed
  tags: always

- name: remove limitrange in {{ admin_project }}
  command: "{{ openshift_cli }} delete limitrange --all -n {{ admin_project }}"
  ignore_errors: true

- name: deploy gogs
  import_tasks: ./gogs.yml
  become: true

- name: check if project quay-enterprise exists
  command: "{{ openshift_cli }} get project quay-enterprise"
  register: quay_project_result
  ignore_errors: true
  changed_when: false
  tags: always

- name: deploy quay
  import_tasks: ./quay.yml
  become: true
  when: quay_project_result is failed
  tags: quay

- name: deploy clair
  import_tasks: ./clair.yml
  become: true
  when: quay_project_result is failed
  tags: quay

- name: deploy nexus
  import_tasks: ./nexus.yml
  become: true
  tags: nexus

- name: deploy sonarqube
  import_tasks: ./sonarqube.yml
  become: true

- name: check if project {{ che_project }} exists
  command: "{{ openshift_cli }} get project {{ che_project }}"
  register: che_project_result
  ignore_errors: true
  changed_when: false
  tags: che

- name: deploy codeready
  command: "{{ openshift_cli }} new-project {{ che_project }}"
  when: che_project_result is failed
  tags: che

- name: remove che limitrange
  command: "{{ openshift_cli }} delete limitrange --all -n {{ che_project }}"
  when: che_project_result is failed
  tags: che

- name: deploy che
  command: "./deploy.sh -d -p={{ che_project }} --enable-oauth"
  args:
    chdir: "{{ tmp_dir }}/files"
  when: che_project_result is failed
  tags: che
  ignore_errors: true

- name: infrastructure tasks complete
  debug:
    msg: "Infrastructure Tasks completed successfully."
