---
# Implement your Post Workload deployment tasks here

- name: delete the remote files used in this role
  file:
    path: "{{tmp_dir}}"
    state: absent
  tags: workload

- name: output workshop info
  debug:
    msg:
    - "user.info: Please run the instructor setup steps first, located here: https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/ProactiveSecurityCompliance/documentation/lab7-instructor-prep.adoc"
    - "Next, follow the lab directions located here: https://github.com/RedHatDemos/SecurityDemos/blob/master/2019Labs/ProactiveSecurityCompliance/documentation/lab7.adoc"
    - "Use a USERID of user1 when following the lab directions."
    - "OpenShift console: https://master.{GUID}.summit.opentlc.com  Username: user1 or admin, password: r3dh4t1!"
  debug:

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
