---
# Implement your Pre Workload deployment tasks here

- name: set gogs facts
  set_fact:
    gogs_generate_user_count: "{{ user_count_end }}"

- name: make the temp dir
  file:
    path: "{{tmp_dir}}"
    state: directory

- name: copy the files used
  copy:
    src: "files"
    dest: "{{tmp_dir}}"

- name: make deploy script
  file:
    path: "{{tmp_dir}}/files/deploy.sh"
    mode: "555"

- name: copy the templates
  template:
    src: "{{ item }}"
    dest: "{{tmp_dir}}/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob: "../templates/*"

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
