---

- name: create the quay-enterprise project
  command: "{{ openshift_cli }} new-project quay-enterprise"

- name: clone the quay operator project
  git:
    repo: https://github.com/redhat-cop/quay-operator.git
    dest: "{{ tmp_dir }}/quay-operator"
    version: master
    force: yes

- name: explicitly switch to the correct branch and tag
  command: "git checkout tags/v1.0.1 -b v1.0.1"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"

- name: create openshift quay objects
  command: "{{ openshift_cli }} create -f {{ item }}"
  args:
    chdir: "{{ tmp_dir }}/quay-operator"
  with_items:
    - deploy/crds/redhatcop.redhat.io_quayecosystems_crd.yaml
    - deploy/service_account.yaml
    - deploy/cluster_role.yaml
    - deploy/cluster_role_binding.yaml
    - deploy/role.yaml
    - deploy/role_binding.yaml
    - deploy/operator.yaml
  ignore_errors: true

- name: grant admin roles
  command: "{{ openshift_cli }} adm policy add-role-to-user admin system:serviceaccount:quay-enterprise:quay-operator -n quay-enterprise"

- name: create the quay secret for pulling the image
  command: "{{ openshift_cli }} create secret docker-registry coreos-pull-secret --docker-server=quay.io  --docker-username='{{ quay_pull_user }}' --docker-password='{{ quay_pull_password }}'"

- name: delete quay limitrange
  command: "{{ openshift_cli }} delete limitrange --all -n quay-enterprise"
  ignore_errors: true

- name: deploy the quay operator
  command: "{{ openshift_cli }} create -f quay_cr.yml"
  args:
    chdir: "{{ tmp_dir}}/files"

- name: wait for quay to deploy
  shell:  "{{ openshift_cli }} get pods  -n quay-enterprise | grep quayecosystem-quay"
  register: result
  until: result.stdout.find("Running") != -1
  retries: 30
  delay: 10

- name: create a secure route for quay
  command: "{{ openshift_cli }} create route edge quay-secure --service=quayecosystem-quay -n quay-enterprise"
  ignore_errors: true
