---
- name: set namespace
  set_fact:
    _namespace: "{{ namespace_prefix }}{{ user_num }}"

- name: Check user{{ user_num }} can login
  command: "oc login --username=user{{ user_num }} --password={{ _user_login_password }} {{ ocwhoami.stdout }} -n {{ _namespace }} --insecure-skip-tls-verify=true --config={{ tmp_dir }}.kube/{{ _namespace }}-config"

- name: Check Fuse workload is running
  command: "oc rollout status DeploymentConfig/pam-fraudmanagement-fuse --watch=true -n {{ _namespace }} --config={{ tmp_dir }}.kube/{{ _namespace }}-config"