apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - default:
        memory: 2048Mi
        cpu: 2000m
      defaultRequest:
        memory: 512Mi
        cpu: 500m
      type: Container
